docs/changelog.md, docs/kerberos.md, docs/openstack-image.md, docs/openstack.md, docs/periscope.md, docs/releasenotes.md, docs/spi.md, mkdocs.yml
Did some minor cleanup, removed some Tech Preview flags/text. Please double-check I got it right. Thx.
=> Minor changes in prep for release of 1.1.0

docs/openstack_pre_prov.md, mkdocs_theme/base.html, mkdocs_theme/providers/openstack_cloudbreak.json
=> CLOUD-51066 Fix documentation of openstack image

docs/azure_pre_prov.md
=> extend WASB description

docs/aws-image.md, docs/gcp-image.md, docs/openstack-image.md
=> CLOUD-51912 removed ambari port

docs/ui_account.md, mkdocs.yml
=> CLOUD-52125 Documentation is needed to 'Cloud Platforms' on GUI

docs/development.md
=> document developer spring cloud consul property

docs/azure.md
@lalyos please review the changes.
=> CLOUD-53135 Update the documentation for Azure Setup with RM Templates

docs/recipes.md, docs/sssd.md, mkdocs.yml
@akanto plz review, suggest, whatever
=> CLOUD-48264 SSSD configuration docs

docs/changelog.md, docs/configuration.md
Please review @aszegedi or @akanto !
=> CLOUD-53136 document configuration ability of ssh fingerprint validation

docs/azure.md
=> CLOUD-51904 cbd: AzureRM missing description how to perform commands

docs/aws.md, docs/azure.md, docs/gcp.md, docs/openstack.md
=> CLOUD-52273 document stack advisor

docs/aws.md, docs/azure.md, docs/gcp.md, docs/openstack.md
=> CLOUD-51906 Document user and cbd details by cloud provider

docs/azure/setup.md, docs/blueprints.md, docs/index.md, docs/releasenotes.md, docs/sssd.md, mkdocs.yml
- Updated release notes to highlight new features vs. tech preview
- cleanup / reorg of blueprints page
- minor cleanup in other spots
=> edits for 1.2.0 release

docs/aws/deployer.md, docs/aws/images.md
=> CLOUD-54734 Move the AWS Setup section to the correct place

Makefile
=> CLOUD-55044 Flow diagram generator

docs/aws/ui/network.md, docs/azure/ui/network.md, docs/gcp/ui/network.md, docs/openstack/ui/network.md
=> update network ui doc

docs/flow.html
=> CLOUD-55044 Fix flow js paths

mkdocs_theme/js/flow.js
=> CLOUD-55044 Fix flow dot paths

docs/development.md
=> Fix run with gradle command

docs/environments.md
=> CLOUD-56645 Fix Gradle bootRun command

docs/diagrams/StackCreationFlowConfig.dot, docs/diagrams/StackStartFlowConfig.dot, docs/diagrams/StackStopFlowConfig.dot, docs/diagrams/StackSyncFlowConfig.dot
=> CLOUD-55042 Fresh flow dots

docs/aws/ui/network.md
=> added description for custom network setup on AWS

Makefile
=> Flow diagram offline copier

Makefile
@schfeca75 sorry for the fix, but make didn't noticed me that the path not exists, so i had to fix
=> Flow diagram offline copier - fix

docs/diagrams/ClusterSyncFlowConfig.dot, mkdocs_theme/js/flow.js
=> CLOUD-58090 Flow Cluster Sync

docs/aws/shell/create.md, docs/aws/ui/create.md
=> added instanceprofile readme

docs/aws/shell/create.md, docs/aws/ui/create.md, docs/azure/shell/create.md, docs/azure/ui/create.md, docs/gcp/shell/create.md, docs/gcp/ui/create.md, docs/openstack/shell/create.md, docs/openstack/ui/create.md
=> CLOUD-58087 instance group can be selected for ambari server

docs/aws/deployer.md
=> define custom cloudformation tag

docs/index.md
@matyix @lalyos - To test the editing process that we've agreed on.
=> Updated index.md with grammar/style edits.

docs/onprem.md
@lalyos @matyix 
**One question** Regarding the following text in the ## Start Cloudbreak section:
"Cloudbreak should start within a minute - you should see a line like this: Started CloudbreakApplication in 36.823 seconds"
What does "Cloudbreak should start within a minute" mean in this sentence? 
Do you meant that "If Cloudbreak started within a minute, you will see a line like this: 'Started CloudbreakApplication in 36.823 seconds'. 
?
=> Updated onprem.md with grammar/style fixes.

docs/releasenotes.md
@lalyos @matyix 
Let me know when you have a draft or a list of fixes/improvements for the next release and I'll help put it together.
=> Updated releasenotes.md. Fixed typos and grammar.

docs/aws/images.md
=> Updated images.md. Just a few edits.

docs/aws/ui/create.md, docs/azure/ui/create.md, docs/gcp/ui/create.md, docs/openstack/ui/create.md
=> CLOUD-56731 ambari username password description added

docs/index.md
=> Updated index.md

docs/architecture.md
A few clarifications for components.
@matyix
=> Updated architecture.md

docs/onprem.md
I added a new section called "Prerequisites" and moved the steps from "System Requirements" there. 
Next, I numbered the steps so that they are easier to follow. I know they don't have to be followed in a specific order, but it was just really hard for me to read them and tell them apart earlier. 
@matyix - please check this. Thanks!
=> Updated onprem.md

docs/aws/deployer.md
Edited so that the content is more understandable.
@lalyos @matyix
=> Updated deployer.md.

docs/aws/shell/example.md, docs/aws/ui/securitygroup.md, docs/azure/shell/example.md, docs/azure/ui/securitygroup.md, docs/gcp/shell/example.md, docs/gcp/ui/securitygroup.md, docs/kerberos.md, docs/openstack/shell/example.md, docs/openstack/ui/securitygroup.md, docs/operations.md, docs/shell/securitygroup.md
=> CLOUD-58966 Remove Cloudbreak Gateway and all of its references

mkdocs_theme/providers/openstack_cloudbreak.json
image is uploaded from kilo
@keyki @akanto please confirm
=> fix openstack image url for 1.3.0 release

docs/openstack/deployer.md
sent to release-1.3.0 branch
@matyix @dbialek2 @lalyos
=> self-signed certs

mkdocs_theme/base.html, mkdocs_theme/providers/openstack_cloudbreak.json
=> CLOUD-60062 openstack image download url creation fix

docs/aws/deployer.md
Just very minor edits. @matyix
=> Updated deployer.md

docs/images.md, mkdocs.yml
=> CLOUD-60311 explain how to override the default images

docs/shell.md
=> CLOUD-60544 Document cbd util cloudbreak-shell-remote command

docs/shell.md
Edited the topic for grammar. Added missing header.
@mhmxs
=> Updated shell.md

docs/azure/setup.md
Edits from my comments in https://github.com/sequenceiq/cloudbreak-docs/pull/80 and some other edits. 
Will add more edits later. 
@mhmxs
=> Updated setup.md

docs/update.md
Added edits that I suggested in https://github.com/sequenceiq/cloudbreak-docs/pull/80. I hope that they are helpful @mhmxs
=> Updated update.md

docs/shell.md
=> CLOUD-61012 Update cloudbreak-shell-remote section to follow changes

docs/operations.md
@matyix @dbialek2 please review!
=> add proxy section to operations

docs/operations.md
=> extend proxy configuration

docs/operations.md
=> Updated operations.md

docs/operations.md
=> CLOUD-61854 Fix ssh description in the documentation

docs/api.md
=> Updated api.md

docs/ui_account.md
=> Updated ui_account.md

docs/periscope.md
=> Updated periscope.md

docs/mesos.md
=> Updated mesos.md

docs/mesos/intro.md
=> Updated intro.md

docs/recipes.md
=> Updated recipes.md

docs/blueprints.md
=> Updated blueprint.md

docs/kerberos.md
=> Updated kerberos.md

Makefile
=> Ability to configure preview port

docs/gcp/shell/template.md, docs/gcp/ui/template.md
=> CLOUD-51841 preemptible documentation added

docs/topologies.md
=> Updated topologies.md

docs/environments.md
Edited according to instructions provided by Marton which helped me to overcome a problem occurring due to out-of-sync master and deployed CBD version.
=> Update environments.md with details of how to load UI files locally for dev environment

docs/index.md
@matyix 
General edits to the intro section.
=> Edited intro section in index.md

docs/architecture.md
=> Formatting fixes in the Architecture section

docs/onprem.md
=> Edits for onprem.md

docs/shell.md
=> Updated shell.md with some minor edits

docs/database.md
=> Updated database.md

docs/environments.md
=> Updated environments.md for readibility and edited content

docs/blueprints.md
=> Edited blueprints.md

docs/topologies.md
=> Fixed typos in topologies.md

docs/images.md
=> Minor edits in edits_imag.md

docs/spi.md
@matyix 
2 Questions about: 
"Consequently, when a new provider is integrated, it immediately becomes a first class citizen in Cloudbreak." (In the first section)
1) What do you mean by a "new provider"? Do you mean that anyone can integrate a new provider with Cloudbreak?
2) The bigger question for this section is: Is this SPI section just informing about how this SPI is implemented in Cloudbreak OR can someone who is a developer and who wants to use Cloudbreak integrate with a provider that Cloudbreak doesn't support yet integrate such a provider?
=> Edited spi.md

docs/configuration.md
Some edits in the file:
- Clarified the section for creating an env specific profile. For example, there was an error, where it said .dev instead of .prod
- Removed the Caveats section and put the info in the beginning (since it was repeated)
- Put Azure commands under Provider Specific Configurations
@matyix
=> Edited configuration.md

docs/operations.md, mkdocs.yml
@matyix 
one question about:
"You can also check the logs of an individual docker container."
What's the syntax for that?
cbd logs <container_name>?
=> updated operations.md and mkdocs.yml (section title change)

docs/gcp/ui/network.md
=> CLOUD-65287 GCP existing VPC improvements

docs/recipes.md
=> CLOUD-65653 Sync recipe documentation with current behavior

docs/update.md
@dbialek2 @matyix @akanto  please review
=> CLOUD-61822 how to upgrade existing clusters from 1.3.0 to 1.4.0

docs/aws/images.md, docs/aws/ui/short.md, docs/azure/setup.md, docs/azure/ui/short.md, docs/environments.md, docs/gcp/images.md, docs/gcp/ui/short.md, docs/mesos/ui/short.md, docs/onprem.md, docs/openstack/images.md, docs/openstack/ui/short.md, docs/topologies.md
This should resolve https://hortonworks.jira.com/browse/BUG-66895.
=> Change Cloudbreak UI from port 3000 to port 443.

docs/aws/shell/create.md, docs/azure/shell/create.md, docs/gcp/shell/create.md, docs/openstack/shell/create.md
=> CLOUD-67919 Update stack create commands

docs/security.md, mkdocs.yml
@dbialek2 could you please review the change?
=> CLOUD75349 Document how to secure cloudbreak installation

docs/common/ports.md
=> Added port for bootstrapping client 9443

docs/releasenotes.md
Based on what @sposetti pointed out in https://hortonworks.jira.com/browse/BUG-80521
@pdarvasi @martonsereg @doktoric  Can you accept the PR and update this content on the live website?
=> Updated RNs for 1.14.4

docs/issues.md
@dbialek2 or @martonsereg pls review
=> EAR-5997 Extend known issues block with the NullPointerException shell bug if template creation commands are after credential selection

docs/issues.md
=> EAR-5997 docs fix

docs/azure/ui/credential.md
@dbialek2 , @sodre90 pls review
=> CLOUD-80103 Use custom role in credential creation

docs/help.md, docs/releasenotes.md, mkdocs.yml
@doktoric  Please review the flex credits doc
I hope this time the process is correct
=> Add flex credits

docs/issues.md
@mhmxs Can you review? What is the jira for this?
=> Added upgrade issue

docs/images.md, mkdocs.yml
Updates related to Custom Images.
=> Updates to Custom Images

docs/update.md
Added a recommendation to back up Cb databases
Per @Jaraxal BUG-92970
=> Update upgrade doc BUG-92970

docs/azure/ui/create.md
Adding new parameter called Encrypt Azure Disks.
Please merge this to 1.16.5 docs and update live docs as well.
CC @sposetti
=> Update azure/create.md w BUG-87603

docs/index.md
Hi @doktoric I am adding a note about the GCP issue. Could you review it (suggest changes if needed), merge it, and push it live? Thanks!
=> Adding a note about the GCP issue

docs/onprem.md
extra space causes command to fail
=> Update onprem.md selinux file location 
